name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: cd app && flutter pub get

      - name: Build IPA
        run: |
          chmod +x ./scripts/build_ios.sh
          ./scripts/build_ios.sh

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: app/build/dist/zero.ipa