name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-ipa:
    runs-on: macos-latest
    name: Build IPA
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: cd app && flutter pub get

      - name: Build IPA
        run: |
          chmod +x ./scripts/build_ios.sh
          ./scripts/build_ios.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: |
            app/build/dist/zero.ipa

  build-apk:
    runs-on: ubuntu-latest
    name: Build APK
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: cd app && flutter pub get

      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      - name: Decode keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > app/android/app/release-key.jks

      - name: Build APK
        run: |
          chmod +x ./scripts/build_android.sh
          ./scripts/build_android.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            app/build/dist/zero.apk